SUPER_CONFIG_PATH: ./configs/r50_deformable_detr_motip_dancetrack.yaml

DATASETS: [MOT17, CrowdHuman, CrowdHuman]
DATASET_SPLITS: [train, train, val]
DATASET_WEIGHTS: [2, 1, 1]

SAMPLE_LENGTHS: [20]
SAMPLE_INTERVALS: [2]
MAX_TEMPORAL_LENGTH: 20

AUG_MAX_SIZE: 1536
AUG_RESIZE_SCALES: [608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 928, 960, 992]

INFERENCE_DATASET:
INFERENCE_SPLIT: ""
INFERENCE_MAX_SIZE: 1536

DET_THRESH: 0.5
NEWBORN_THRESH: 0.5
ID_THRESH: 0.02

DETR_PRETRAIN: ./pretrains/r50_deformable_detr_coco_mot17.pth

EPOCHS: 45
SCHEDULER_MILESTONES: [30, 40, ]
LR_WARMUP_EPOCHS: 2

NUM_ID_VOCABULARY: 200
TRAINING_NUM_ID: 80

# extra argument :D
MANUAL_OUTPUT_DIR: ""
SEQ_PATH: "/usr/users/vhassle/datasets/Wortschatzinsel/5k_subset_12_42.mkv"
VIEW: "no_specifc_view"
